account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

    path('login/', views.login, name='login'),

    path('logout/', views.logout, name='logout'),
]

facebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('post.urls')),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/like/', views.like, name='like'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),

    path('create/', views.create, name='create'),

    path('<int:post_id>/like/', views.like, name='like'),
]

account/models.py
from django.db import models

post/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')

post/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', )

account/views.py
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('account:login')
    else:
        form = UserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'account/forms.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('post:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'account/forms.html', context)


def logout(request):
    auth_logout(request)
    return redirect('account:login')

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.


def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    
    context = {
        'form': form,
    }

    return render(request, 'accounts/forms.html', context)


def login(request):

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())

            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    
    context = {
        'form': form,
    }

    return render(request, 'accounts/forms.html', context)


def logout(request):

    auth_logout(request)

    return redirect('accounts:login')
    

post/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PostForm
from .models import Post


def index(request):
    context = {
        'posts': Post.objects.all(),
    }
    return render(request, 'post/index.html', context)


def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('post:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request, 'post/forms.html', context)


def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    if post.like_users.filter(username=user.username):
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('post:index')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post

# Create your views here.


def index(request):

    posts = Post.objects.all()

    context = {
        'posts': posts,
    }

    return render(request, 'posts/index.html', context)


def create(request):

    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():

            post = form.save(commit=False)
            post.user = request.user
            post.save()

            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request, 'posts/forms.html', context)


def like(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if post.like_users.filter(user=user):
        post.like_users.remove(user)
    else:
        post.like_users.add(user)

    return redirect('posts:index')
    

facebook/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Facebook</title>
  </head>
  <body>
    {% if user.is_authenticated %}
      <p>Hi, {{user.username}}!</p>
      <a href="{% url 'account:logout' %}">Logout</a>
      <a href="{% url 'post:create' %}">Write</a>
    {% else %}
      <a href="{% url 'account:signup' %}">Signup</a>
      <a href="{% url 'account:login' %}">Login</a>
    {% endif %}
    {% block body %}
    {% endblock %}
  </body>
</html>

post/templates/post/forms.html
{% extends 'base.html' %}

{% block body %}
  <h1>Create</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{form.as_table}}
    </table>
    <input type="submit" value="submit" />
  </form>
{% endblock %}

post/templates/post/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>Index</h1>
  {% for post in posts %}
    <h4>{{post.user.username}}</h4>
    <h4>{{post.title}}</h4>
    <hr>
    {% if user in post.like_users.all %}
      <a href="{% url 'post:like' post.id %}">Unlike</a>
    {% else %}
      <a href="{% url 'post:like' post.id %}">Like</a>
    {% endif %}
  {% endfor %}
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block body %}

  <h1>Index</h1>

  {% for post in posts %}

    <h4>{{post.user.username}}</h4>
    <h4>{{post.title}}</h4>
    
    <hr>

    {% if user in post.like_users.all %}
      <a href="{% url 'posts:like' post.id %}">Like cancel</a>
    {% else %}
      <a href="{% url 'posts:like' post.id %}">Like</a>
    {% endif %}

  {% endfor %}

{% endblock %}